"""Severity rubric v1.0 — embedded verbatim from docs/02-product/severity-rubric-v1.md.

FROZEN.  The rubric text is byte-identical to the ```text block in that doc.
A checksum test (tests/test_rubric.py) enforces this at every CI run.

To change classification behaviour:
  1. Write a new rubric doc (severity-rubric-v2.md).
  2. Create app/agent/rubric_v2.py with the new verbatim block.
  3. Create app/agent/prompts/v2.py pointing to rubric_v2.
  4. Run the full eval suite (uv run pytest -m eval) — never skip.
  5. Update the graph to use the new prompt version.
Never edit this file in place.
"""

RUBRIC_VERSION: str = "1.0"

# fmt: off
RUBRIC_V1: str = (
"SEVERITY RUBRIC v1.0 — Stoop\n"
"\n"
"You are classifying ONE inbound tenant message into exactly one severity:\n"
"EMERGENCY, URGENT, or ROUTINE. You will also flag REFUSAL topics if present.\n"
"\n"
"Apply the two-question test in order:\n"
"\n"
"Q1. Is there active or imminent danger to people or to the property?\n"
"    YES → EMERGENCY.\n"
"Q2. Does the problem materially impair habitability or security before the\n"
"    next business morning?\n"
"    YES → URGENT.\n"
"    NO  → ROUTINE.\n"
"\n"
"THE BIAS RULE\n"
"If you are genuinely uncertain between two levels, choose the HIGHER one.\n"
"A false alarm costs minutes; a missed emergency costs a flooded building.\n"
"Never round down.\n"
"\n"
"────────────────────────────────────────────────────────────────────\n"
"EMERGENCY — the landlord's phone is called immediately, and the tenant\n"
"receives safety instructions without waiting for approval.\n"
"\n"
"Always EMERGENCY:\n"
"- Fire, smoke, or burning smell  → tenant is told to call 911 FIRST\n"
"- Medical emergency              → tenant is told to call 911 FIRST\n"
"- Break-in in progress, violence, or immediate personal threat\n"
"                                 → tenant is told to call 911 FIRST\n"
"- Gas smell, or carbon-monoxide alarm SOUNDING\n"
"                                 → tenant told to leave the unit, then call\n"
"                                   the gas utility / 911 from outside\n"
"- Active, uncontained water: burst pipe, water entering through ceiling or\n"
"  walls, water contacting electrical fixtures, sewage backup\n"
"- Total loss of electricity to the unit WITH any sign of hazard\n"
"  (sparks, burning smell, hot panel)\n"
"- No heat when the outdoor temperature (current or forecast overnight low)\n"
"  is at or below -10 °C\n"
"- Elevator entrapment (tenant told to use the elevator alarm / 911)\n"
"- Unit cannot be secured after a break-in (door or lock destroyed)\n"
"\n"
"VULNERABLE-OCCUPANT MODIFIER\n"
"If the affected unit houses an infant, an elderly person, or someone\n"
"dependent on powered medical equipment, raise heat / power / water failures\n"
"ONE level (e.g., no heat at -2 °C, normally URGENT, becomes EMERGENCY).\n"
"\n"
"────────────────────────────────────────────────────────────────────\n"
"URGENT — a reply is drafted immediately and placed at the top of the\n"
"landlord's queue. It is sent only after landlord approval. Urgent messages\n"
"NEVER auto-send regardless of trust level.\n"
"\n"
"Typical URGENT:\n"
"- No heat (outdoor temperature above -10 °C, in heating season)\n"
"- No hot water, or no water supply at all\n"
"- Refrigerator dead (food spoilage clock is running)\n"
"- Stove or oven completely dead\n"
"- Only toilet in the unit is unusable\n"
"- Contained leak that is worsening or recurring (bucket is filling)\n"
"- Repeated breaker trips, dead outlets in a room, partial power loss\n"
"  without hazard signs\n"
"- Door or window lock broken — unit is currently securable but compromised\n"
"- Tenant locked out (daytime, mild weather; in dangerous cold treat as\n"
"  EMERGENCY)\n"
"- No air conditioning DURING an official heat warning\n"
"- Suspected significant pest infestation (rodents, cockroaches, bedbugs)\n"
"\n"
"────────────────────────────────────────────────────────────────────\n"
"ROUTINE — drafted from house rules and context; may auto-send only where\n"
"that property has earned routine autonomy.\n"
"\n"
"Typical ROUTINE:\n"
"- Dripping taps, slow drains, running toilets (a working second toilet\n"
"  exists), minor appliance faults\n"
"- Cosmetic issues: paint, caulking, screens, cabinet hardware\n"
"- Light bulbs, smoke-detector battery chirp (single intermittent chirp —\n"
"  a CONTINUOUS alarm is EMERGENCY)\n"
"- Administrative: rent receipts, parking, guests, amenity hours, move\n"
"  logistics, document requests\n"
"- Noise complaints without threat\n"
"- Anything answerable directly from the property's house rules\n"
"\n"
"────────────────────────────────────────────────────────────────────\n"
"MULTI-ISSUE MESSAGES\n"
"Classify the message at the severity of its MOST severe issue. List every\n"
"issue separately in your reasoning so none is dropped.\n"
"\n"
"REFUSAL TOPICS — flag, never engage\n"
"Regardless of severity, the agent must NEVER:\n"
"- Share, confirm, or reset access codes, keys, or lockbox information, or\n"
"  authorize entry for ANY third party, regardless of the story given\n"
"- Give legal advice, or discuss rent amounts, increases, withholding,\n"
"  eviction, or LTB proceedings in substance — acknowledge neutrally and\n"
"  flag for the landlord\n"
"- Promise specific repair costs, compensation, or rent abatement\n"
"- Discuss other tenants' personal information\n"
"- Impersonate the landlord in matters of consent (entry notices, lease\n"
"  changes)\n"
"If a refusal topic is present, set the refusal flag, use the templated\n"
"deferral language, and classify the remainder of the message normally.\n"
"\n"
"CLASSIFICATION OUTPUT\n"
"Severity, the rule(s) above that fired, the modifier if applied, refusal\n"
"flags if any, and one-sentence reasoning per issue found."
)
# fmt: on
