/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as EarlyAccessRouteImport } from './routes/early-access'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPropertiesRouteImport } from './routes/app.properties'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AppPropertiesIdRouteImport } from './routes/app.properties.$id'
import { Route as AppConversationsIdRouteImport } from './routes/app.conversations.$id'
import { Route as AppPropertiesIdTrustRouteImport } from './routes/app.properties.$id.trust'
import { Route as AppPropertiesIdSettingsRouteImport } from './routes/app.properties.$id.settings'
import { Route as AppConversationsIdEmergencyRouteImport } from './routes/app.conversations.$id.emergency'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessRoute = EarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIdRoute = AppPropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPropertiesRoute,
} as any)
const AppConversationsIdRoute = AppConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIdTrustRoute = AppPropertiesIdTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AppPropertiesIdRoute,
} as any)
const AppPropertiesIdSettingsRoute = AppPropertiesIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppPropertiesIdRoute,
} as any)
const AppConversationsIdEmergencyRoute =
  AppConversationsIdEmergencyRouteImport.update({
    id: '/emergency',
    path: '/emergency',
    getParentRoute: () => AppConversationsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/design-system': typeof DesignSystemRoute
  '/early-access': typeof EarlyAccessRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/app/account': typeof AppAccountRoute
  '/app/activity': typeof AppActivityRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/conversations/$id': typeof AppConversationsIdRouteWithChildren
  '/app/properties/$id': typeof AppPropertiesIdRouteWithChildren
  '/app/conversations/$id/emergency': typeof AppConversationsIdEmergencyRoute
  '/app/properties/$id/settings': typeof AppPropertiesIdSettingsRoute
  '/app/properties/$id/trust': typeof AppPropertiesIdTrustRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/design-system': typeof DesignSystemRoute
  '/early-access': typeof EarlyAccessRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/app/account': typeof AppAccountRoute
  '/app/activity': typeof AppActivityRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/conversations/$id': typeof AppConversationsIdRouteWithChildren
  '/app/properties/$id': typeof AppPropertiesIdRouteWithChildren
  '/app/conversations/$id/emergency': typeof AppConversationsIdEmergencyRoute
  '/app/properties/$id/settings': typeof AppPropertiesIdSettingsRoute
  '/app/properties/$id/trust': typeof AppPropertiesIdTrustRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/design-system': typeof DesignSystemRoute
  '/early-access': typeof EarlyAccessRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/app/account': typeof AppAccountRoute
  '/app/activity': typeof AppActivityRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/conversations/$id': typeof AppConversationsIdRouteWithChildren
  '/app/properties/$id': typeof AppPropertiesIdRouteWithChildren
  '/app/conversations/$id/emergency': typeof AppConversationsIdEmergencyRoute
  '/app/properties/$id/settings': typeof AppPropertiesIdSettingsRoute
  '/app/properties/$id/trust': typeof AppPropertiesIdTrustRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/checkout'
    | '/design-system'
    | '/early-access'
    | '/onboarding'
    | '/plans'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/app/account'
    | '/app/activity'
    | '/app/properties'
    | '/app/conversations/$id'
    | '/app/properties/$id'
    | '/app/conversations/$id/emergency'
    | '/app/properties/$id/settings'
    | '/app/properties/$id/trust'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/checkout'
    | '/design-system'
    | '/early-access'
    | '/onboarding'
    | '/plans'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/app/account'
    | '/app/activity'
    | '/app/properties'
    | '/app/conversations/$id'
    | '/app/properties/$id'
    | '/app/conversations/$id/emergency'
    | '/app/properties/$id/settings'
    | '/app/properties/$id/trust'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/checkout'
    | '/design-system'
    | '/early-access'
    | '/onboarding'
    | '/plans'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/app/account'
    | '/app/activity'
    | '/app/properties'
    | '/app/conversations/$id'
    | '/app/properties/$id'
    | '/app/conversations/$id/emergency'
    | '/app/properties/$id/settings'
    | '/app/properties/$id/trust'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  DesignSystemRoute: typeof DesignSystemRoute
  EarlyAccessRoute: typeof EarlyAccessRoute
  OnboardingRoute: typeof OnboardingRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access': {
      id: '/early-access'
      path: '/early-access'
      fullPath: '/early-access'
      preLoaderRoute: typeof EarlyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/properties': {
      id: '/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties/$id': {
      id: '/app/properties/$id'
      path: '/$id'
      fullPath: '/app/properties/$id'
      preLoaderRoute: typeof AppPropertiesIdRouteImport
      parentRoute: typeof AppPropertiesRoute
    }
    '/app/conversations/$id': {
      id: '/app/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/app/conversations/$id'
      preLoaderRoute: typeof AppConversationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties/$id/trust': {
      id: '/app/properties/$id/trust'
      path: '/trust'
      fullPath: '/app/properties/$id/trust'
      preLoaderRoute: typeof AppPropertiesIdTrustRouteImport
      parentRoute: typeof AppPropertiesIdRoute
    }
    '/app/properties/$id/settings': {
      id: '/app/properties/$id/settings'
      path: '/settings'
      fullPath: '/app/properties/$id/settings'
      preLoaderRoute: typeof AppPropertiesIdSettingsRouteImport
      parentRoute: typeof AppPropertiesIdRoute
    }
    '/app/conversations/$id/emergency': {
      id: '/app/conversations/$id/emergency'
      path: '/emergency'
      fullPath: '/app/conversations/$id/emergency'
      preLoaderRoute: typeof AppConversationsIdEmergencyRouteImport
      parentRoute: typeof AppConversationsIdRoute
    }
  }
}

interface AppPropertiesIdRouteChildren {
  AppPropertiesIdSettingsRoute: typeof AppPropertiesIdSettingsRoute
  AppPropertiesIdTrustRoute: typeof AppPropertiesIdTrustRoute
}

const AppPropertiesIdRouteChildren: AppPropertiesIdRouteChildren = {
  AppPropertiesIdSettingsRoute: AppPropertiesIdSettingsRoute,
  AppPropertiesIdTrustRoute: AppPropertiesIdTrustRoute,
}

const AppPropertiesIdRouteWithChildren = AppPropertiesIdRoute._addFileChildren(
  AppPropertiesIdRouteChildren,
)

interface AppPropertiesRouteChildren {
  AppPropertiesIdRoute: typeof AppPropertiesIdRouteWithChildren
}

const AppPropertiesRouteChildren: AppPropertiesRouteChildren = {
  AppPropertiesIdRoute: AppPropertiesIdRouteWithChildren,
}

const AppPropertiesRouteWithChildren = AppPropertiesRoute._addFileChildren(
  AppPropertiesRouteChildren,
)

interface AppConversationsIdRouteChildren {
  AppConversationsIdEmergencyRoute: typeof AppConversationsIdEmergencyRoute
}

const AppConversationsIdRouteChildren: AppConversationsIdRouteChildren = {
  AppConversationsIdEmergencyRoute: AppConversationsIdEmergencyRoute,
}

const AppConversationsIdRouteWithChildren =
  AppConversationsIdRoute._addFileChildren(AppConversationsIdRouteChildren)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppActivityRoute: typeof AppActivityRoute
  AppPropertiesRoute: typeof AppPropertiesRouteWithChildren
  AppConversationsIdRoute: typeof AppConversationsIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppActivityRoute: AppActivityRoute,
  AppPropertiesRoute: AppPropertiesRouteWithChildren,
  AppConversationsIdRoute: AppConversationsIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  DesignSystemRoute: DesignSystemRoute,
  EarlyAccessRoute: EarlyAccessRoute,
  OnboardingRoute: OnboardingRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
